# Lists, Dictionaries and Sets in Python

## Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [254]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]

List can also be created by using list() function. 

In [255]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


### Question 1
Adding to an existing list

Add 10 to list l1 given above

*Hint:  Use `append()`*

In [256]:
l1.append(10)
print('Appending 10 to list l1: ',l1)

Appending 10 to list l1:  ['learning', 'Python', 'is fun?', True, 10]


### Question 2
Removing from an existing list

Remove 10 from l1

*Hint: use `remove()`*

In [257]:
l1.remove(10)
print('After removing 10 from list l1',l1)

After removing 10 from list l1 ['learning', 'Python', 'is fun?', True]


### Question 3
Join 2 lists l1 and l2

Hint: use **`+`** operator or **`extend()`**

In [258]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [259]:
l1.extend(l2)
print('Concat: ',l1)

Concat:  ['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]


### Question 4
Number List

Find Range and Mean of l3.

`l3 = [2,4,6,8]`

Hint: use **`len()`, `sum()`, `min()`, `max()`** functions
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [260]:
import numpy as np
l3 = [2,4,6,8]
print('Mean: ',np.mean(l3))

Mean:  5.0


In [261]:
print('Range: ',max(l3)-min(l3))

Range:  6


### Question 5
Count the occurances of an element in a given list

Append the given sequence of numbers to l3 (given above)

0, 1, 3, 3, 5, 5, 7, 9

Count the occurences of 5 in l3.

Hint: use **`+`** operator to add multiple elements in the array and **`count()`** function to print the occurences

In [262]:
l3 = l3+[0,1,3,3,5,5,7,9]
print('Count of 5 in list l3: ',l3.count(5))

Count of 5 in list l3:  2


### Question 6
Sorting and Reversing a list

sort and print l3 in ascending and descending order sequentially (given above)

Hint: use **`sort()`** function

In [263]:
l3.sort()
print('Sorting list l3: ',l3)

Sorting list l3:  [0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]


In [264]:
l3.reverse()
print('Printing list l3 in reverse: ',l3)

Printing list l3 in reverse:  [9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]


## Functions

**Example:**

**def** function_name(args)**:**

    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [265]:
def sum_3(n1,n2,n3):
    return n1+n2+n3

## Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [266]:
f=lambda n1,n2,n3 : n1+n2+n3


In [267]:
f(1,2,3)

6

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding rows, columns and operating on 2d matrices aren't readily available. So, we will use ***Numpy*** for such functions.



In [268]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [269]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Some functions on np.array()

In [270]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

Hint: You can also use **`np.identity()`** function

In [271]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9, 8, 7, 6, 5, 4, 3, 2, 1 arranged in the same order

Use: **`np.matrix()`** function



In [272]:
l4=[[9,8,7],[6,5,4],[3,2,1]]

In [273]:
mat = np.matrix(l4)
print(mat)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**

In [274]:
mat.T

matrix([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

### Question 4
Add (+) 1 to all the elements in the given matrix.

In [275]:
arr+1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.

nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [276]:
nd6=np.matrix([[ 1,4,9,121,144,169],[ 16,25,36,196,225,256],[ 49,64,81,289,324,361]])

In [277]:
print(nd6.mean())

131.66666666666666


### Question 6

Find the dot product of two given matrices.

Hint: use **`np.dot()`**

In [278]:
nd7=np.matrix([[ 1,2,3],[4,5,6],[7,8,9]])
nd8=np.matrix([[ 9,8,7],[6,5,4],[3,2,1]])

In [279]:
np.dot(nd7,nd8)

matrix([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

# Pandas

We have seen Numpy in the last section. It is good at performing math operations on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](https://pandas.pydata.org/pandas-docs/stable/)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [280]:
import pandas as pd

In [281]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

Hint: use **`.Series`**

In [282]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [283]:
series2 = pd.Series(d1)
print(series2)

a    1
b    2
c    3
dtype: int64


You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


Hint: use **`np.dot()`**

In [284]:
np.dot(series1,series2)

14

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [285]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [286]:
df1.iloc[1]

a    2
b    4
c    7
Name: 1, dtype: int64

### Question 4

Select column c in second row of df1.

Hint: For using labels use **`df.loc[row, column]`**

For using numeric indexed use **`df.iloc[]`**

For using mixture of numeric indexes and labels use **`df.ix[row, column]`**



In [287]:
df1.loc[1,'c']

7

## Using Dataframes on a dataset

### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

1. mpg 	Miles/(US) gallon
2. cyl 	Number of cylinders
3. disp 	Displacement (cu.in.)
4. hp 	Gross horsepower
5. drat 	Rear axle ratio
6. wt 	Weight (1000 lbs)
7. qsec 	1/4 mile time
8. vs 	Engine (0 = V-shaped, 1 = straight)
9. am 	Transmission (0 = automatic, 1 = manual)
10. gear 	Number of forward gears
11. carb 	Number of carburetors 


In [288]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']

Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


Hint: use **`type()`** and **`df.shape`**

In [289]:
print(type(mtcars))
print(mtcars.shape)

<class 'pandas.core.frame.DataFrame'>
(32, 12)


### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

Hint: use **`.head()`** and **`.tail()`**

In [290]:
print(mtcars.head(10))
print(mtcars.tail(10))

                                name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                      Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                  Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                    Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                    Merc 280  19.2    6  167.6  123  3.92  3.440   

                    qsec  vs  am  gear  carb  
name                                    

### Question 7

Print all the column labels in the given dataset - mtcars.

Hint: use **`df.columns`**

In [291]:
print(mtcars.columns)

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')


### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

Hint: **`mtcars.ix[:, :]`** gives all rows and columns in the dataset

In [292]:
mtcars.iloc[:6,:3]

name   mpg  cyl
name                                           
Mazda RX4                  Mazda RX4  21.0    6
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6
Datsun 710                Datsun 710  22.8    4
Hornet 4 Drive        Hornet 4 Drive  21.4    6
Hornet Sportabout  Hornet Sportabout  18.7    8
Valiant                      Valiant  18.1    6

# Lab Brief - Statistical Learning with Python

## Part-1

## Measures of Data

Descriptive Statistcs are measures that summarize important features of data. Producing these descriptive statistics is a common first step to take after cleaning and preparing a dataset for further analysis. Examples are like calculating Mean or Median. In this lab, we will be looking into some of these functions and explore several new ones.

#### Measures of Central Tendency

Whenever you measure things of the same kind, a fairly large number of such measurements will tend to cluster around the middle value. Such a value is called a measure of "Central Tendency". The other terms that are used synonymously are "Measures of Location", or "Statistical Averages". 

In [293]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

mtcars = pd.read_csv('mtcars.csv')

#### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

1. mpg 	Miles/(US) gallon
2. cyl 	Number of cylinders
3. disp 	Displacement (cu.in.)
4. hp 	Gross horsepower
5. drat 	Rear axle ratio
6. wt 	Weight (1000 lbs)
7. qsec 	1/4 mile time
8. vs 	Engine (0 = V-shaped, 1 = straight)
9. am 	Transmission (0 = automatic, 1 = manual)
10. gear 	Number of forward gears
11. carb 	Number of carburetors 

#### Explore the data - Setting the index

In [294]:
mtcars.index = mtcars["name"]
mtcars.head()

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2

### Question 1

What is the first car name given in mtcars?

Make use of index which has been set previously

Hint: Use **`.loc`** function


In [295]:
mtcars.loc[mtcars.index[0],'name']

'Mazda RX4'

### Question 2
What is the highest difference between the hp and cyl?

**Hint:** You can use **max()** function to find the difference

In [306]:
max(mtcars['hp']-mtcars['cyl'])

327

### Question 3
What are the cars having highest weight(wt) and lowest weight(wt)?

**Hint:** Use idxmax() and idxmin() to locate the row

**Note:** Both idxmax and idxmin belong to pandas

In [297]:
mtcars['wt'].idxmax()

'Lincoln Continental'

In [298]:
mtcars['wt'].idxmin()

'Lotus Europa'

### Question 4

Find the mean of each row and each column in the given dataset.

**Hint:** Use .mean() function. To operate on rows use **axis=0**, on columns use **axis=1**

In [299]:
print(mtcars.mean(axis=0))
print(mtcars.mean(axis=1))

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64
name
Mazda RX4              29.907273
Mazda RX4 Wag          29.981364
Datsun 710             23.598182
Hornet 4 Drive         38.739545
Hornet Sportabout      53.664545
Valiant                35.049091
Duster 360             59.720000
Merc 240D              24.634545
Merc 230               27.233636
Merc 280               31.860000
Merc 280C              31.787273
Merc 450SE             46.430909
Merc 450SL             46.500000
Merc 450SLC            46.350000
Cadillac Fleetwood     66.232727
Lincoln Continental    66.058545
Chrysler Imperial      65.972273
Fiat 128               19.440909
Honda Civic            17.742273
Toyota Corolla         18.814091
Toyota Corona          24.888636
Dodge Challenger       47.240909
AMC Javelin            46.007727
Camaro Z28  

## Part 2

## Measures of Dispersion

Measures of Dispersion (Spread) are statistics that describe how data varies. Measure of dispersion gives us the sense of how much the data tends to diverge from the central tendency.

### Question 5

What is the range of `mpg` in the given dataset?

**Hint:** Range = max - min

In [300]:
max(mtcars['mpg']) - min(mtcars['mpg'])

23.5

### Question 6

Calculate the 25th quantile (lower quantile) for `mpg` in the given dataset.

**Hint:** Use **.quantile()**

In [301]:
mtcars['mpg'].quantile(.25)

15.425

### Question 7

Calculate the Inter-Quartile Range (IQR) for `mpg` in the given dataset.

Interquartile range (IQR) is another common measure of spread. IQR is the distance between the 3rd quartile and the 1st quartile.

**Hint:** IQR = Q3 - Q1

In [302]:
mtcars['mpg'].quantile(.75)-mtcars['mpg'].quantile(.25)

7.375

### Question 8

Calculate the Variance, Standard Deviation and Mean Absolute Deviation for `mpg`.

Variance and Standard Deviation are two other common measure of dispersion.

**Hint:** Use .var() and .std() and .mad()

In [303]:
mtcars['mpg'].var()

36.32410282258065

In [304]:
mtcars['mpg'].std()

6.026948052089105

In [305]:
mtcars['mpg'].mad()

4.714453125